### ISSUE TITLE
flutter player 什么时候支持空安全

### ISSUE THREAD

**Issue by lan2000** [tencentyun/SuperPlayer#25]

**Comment by lan2000** [comment]
另外和另一个tencent_trtc_cloud同时使用SDK会冲突

**Comment by lan2000** [comment]
> 另外和另一个tencent_trtc_cloud同时使用SDK会冲突

用这个tencent_trtc_cloud_professional

**Comment by steve0755** [comment]
> _No description provided._

**Comment by steve0755** [comment]
> > _No description provided._

https://github.com/tencentyun/SuperPlayer/commit/ab42bb368bbb093c3d5fd790b1451e7dea5c7e64

**Comment by steve0755** [comment]
> > > _No description provided._
> 
> [ab42bb3](https://github.com/tencentyun/SuperPlayer/commit/ab42bb368bbb093c3d5fd790b1451e7dea5c7e64)

已经修复，空安全的修复试试这个提交。
