### ISSUE TITLE
按照文档集成，报错，提示“don't support null safety”

### ISSUE THREAD

**Issue by itlws** [tencentyun/SuperPlayer#3]
按照文档集成，运行报错，提示：
`Error: Cannot run with sound null safety, because the following dependencies
don't support null safety:

 - package:super_player
`

**Comment by dokieyang** [comment]
已经支持， 请更新下到最新代码

**Comment by FiShelly** [comment]
../../../.pub-cache/git/SuperPlayer-2f83b039d44ceaa568d68513678a65cb78c09415/Flutter/lib/super_player.dart:1:1: Error: A library can't opt out of null safety by default, when using sound null safety.
// @dart = 2.7
![image](https://user-images.githubusercontent.com/16427792/134302730-0b452f8f-61a6-413d-8fa7-90ded3e30530.png)
貌似还是不行。

**Comment by YXCQU** [comment]
在你的main文件添加   // @Dart = 2.7
